server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#其他配置
netease:
  jdbc:
   enable: false
